<?php
$typeArr[1] = '公司简介';
$typeArr[2] = '产品中心';
$typeArr[3] = '工程案例';
$typeArr[4] = '服务流程';
$typeArr[5] = '服务承诺';
$typeArr[6] = '沐森新闻';
$typeArr[7] = '联系我们';
$typeArr[8] = '行业动态';
$typeArr[9] = '新闻中心';
$typeArr[10] = '新风系统';
$typeArr[12] = '净水器';
$typeArr[13] = '美国托马仕新风';
$typeArr[22] = '斯麦恩';
$typeArr[25] = '空调';
$typeArr[26] = '吸尘';
$typeArr[30] = '地暖';
$typeArr[32] = '空气净化器';
$typeArr[34] = '日本三菱空调';
$typeArr[37] = '意大利DADAHOME中央吸尘';
$typeArr[47] = '德国哈姆地暖';
$typeArr[52] = '三菱重工';
?>