<?php
$z[0]=Array("field","",196,215);
$z[0][4]['name']="title";
$z[1]=Array("global","",216,242);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",282,304);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",343,394);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1031,1066);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1306,1325);
$z[5][4]['name']="title";
$z[6]=Array("field","",1422,1440);
$z[6][4]['name']="body";
$z[7]=Array("arclist","\n      <a href=\"[field:arcurl/]\">\n      <div class=\"col-lg-4 col-sm-6 col-xs-12\">\n        <picture><img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\"/></picture>\n        <p>[field:title/]</p>\n      </div>\n      </a>\n      ",2212,2500);
$z[7][4]['row']="3";
$z[7][4]['pagesize']="20";
$z[7][4]['titlelen']="45";
$z[8]=Array("include","",2570,2607);
$z[8][4]['filename']="footer.htm";

?>