<a href="[field:arcurl/]">
    <div class="col-lg-4 col-sm-6 col-xs-12" title="[field:fulltitle/]">
      <div class="new-img"> <img src="[field:litpic/]" alt="[field:fulltitle/]"> </div>
      <div class="new-img2">
        <li>[field:title/]...</li>
        <p>[field:description function="cn_substr(@me,56)"/]...</p>
        <span>[field:pubdate function='strftime("Y-%m-%d",@me)'/]</span> </div>
    </div>
    </a>