<?php
$z[0]=Array("global","",202,228);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",272,302);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",339,366);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",844,879);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\r\n<a href=\"[field:arcurl/]\">\r\n<div class=\"col-lg-3 col-sm-6 col-xs-12\">\r\n<div class=\"course-list-img\">\r\n<img src=\"[field:litpic/]\">\r\n<div class=\"case-ms\">\r\n<h4>[field:title/]</h4>\r\n<p></p>\r\n[field:info/]... </div>\r\n</div>\r\n<li>[field:title/]</li>\r\n</div>\r\n</a>\r\n",2044,2392);
$z[4][4]['typeid']="3";
$z[4][4]['row']="8";
$z[4][4]['titlelen']="30";
$z[4][4]['infolen']="120";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]<span>[field:pubdate function='strftime(\"Y-%m-%d\",@me)'/]</span></a></li>\r\n",4365,4588);
$z[5][4]['typeid']="6";
$z[5][4]['row']="8";
$z[5][4]['titlelen']="30";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("arclist","\r\n<li><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]<span>[field:pubdate function='strftime(\"Y-%m-%d\",@me)'/]</span></a></li>\r\n",4697,4920);
$z[6][4]['typeid']="8";
$z[6][4]['row']="8";
$z[6][4]['titlelen']="30";
$z[6][4]['orderby']="pubdate";
$z[7]=Array("include","",5649,5686);
$z[7][4]['filename']="footer.htm";

?>