<?php
$z[0]=Array("global","",196,222);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",265,295);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",331,358);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",822,857);
$z[3][4]['filename']="head.htm";
$z[4]=Array("arclist","\n<a href=\"[field:arcurl/]\">\n<div class=\"col-lg-3 col-sm-6 col-xs-12\">\n<div class=\"course-list-img\">\n<img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\">\n<div class=\"case-ms\">\n<h4>[field:title/]</h4>\n<p></p>\n[field:info/]... </div>\n</div>\n<li>[field:title/]</li>\n</div>\n</a>\n",1990,2350);
$z[4][4]['typeid']="3";
$z[4][4]['row']="8";
$z[4][4]['titlelen']="45";
$z[4][4]['infolen']="120";
$z[4][4]['orderby']="pubdate";
$z[5]=Array("arclist","\n<li><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]<span>[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</span></a></li>\n",4261,4483);
$z[5][4]['typeid']="6";
$z[5][4]['row']="8";
$z[5][4]['titlelen']="45";
$z[5][4]['orderby']="pubdate";
$z[6]=Array("arclist","\n<li><a href=\"[field:arcurl/]\" title=\"[field:fulltitle/]\">[field:title/]<span>[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</span></a></li>\n",4586,4808);
$z[6][4]['typeid']="8";
$z[6][4]['row']="8";
$z[6][4]['titlelen']="45";
$z[6][4]['orderby']="pubdate";
$z[7]=Array("include","",5503,5540);
$z[7][4]['filename']="footer.htm";
$z[8]=Array("flink","",5574,5587);

?>