<?php
$z[0]=Array("field","",196,219);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",220,246);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",286,308);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",347,398);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1035,1070);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1529,1558);
$z[5][4]['name']="position";
$z[6]=Array("list","\n   <a href=\"[field:arcurl/]\">\n    <div class=\"col-lg-4 col-sm-6 col-xs-12\" title=\"[field:fulltitle/]\">\n      <div class=\"new-img\"> <img src=\"[field:litpic/]\" alt=\"[field:fulltitle/]\"> </div>\n      <div class=\"new-img2\">\n        <li>[field:title/]...</li>\n        <p>[field:description function=\"cn_substr(@me,84)\"/]...</p>\n        <span>[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/]</span> </div>\n    </div>\n    </a>\n   ",1877,2364);
$z[6][4]['row']="9";
$z[6][4]['pagesize']="10";
$z[6][4]['titlelen']="30";
$z[7]=Array("pagelist","",2469,2540);
$z[7][4]['listitem']="info,index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",2634,2671);
$z[8][4]['filename']="footer.htm";

?>