<?php
$z[0]=Array("field","",196,219);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",220,246);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",286,315);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",354,412);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1049,1084);
$z[4][4]['filename']="head.htm";
$z[5]=Array("channel","\n<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n",1448,1550);
$z[5][4]['type']="topone";
$z[6]=Array("channel","\n <li><a href='[field:typelink/]'>[field:typename/]</a></li> \n",1551,1715);
$z[6][4]['type']="self";
$z[6][4]['currentstyle']="<li><a href='~typelink~' >~typename~</a></li>";
$z[7]=Array("list","\n     <a href=\"[field:arcurl/]\">\n    <div class=\"col-lg-4 col-sm-6 col-xs-12\">\n      <div class=\"course-list-img\"> <img src=\"[field:litpic/]\">\n        <div class=\"case-ms\">[field:description function=\"cn_substr(@me,84)\"/]... </div>\n      </div>\n      <li>[field:title/]</li>\n    </div>\n    </a>\n ",1776,2132);
$z[7][4]['row']="15";
$z[7][4]['pagesize']="10";
$z[7][4]['titlelen']="30";
$z[8]=Array("pagelist","",2240,2311);
$z[8][4]['listitem']="info,index,end,pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",2682,2719);
$z[9][4]['filename']="footer.htm";

?>