<?php
$z[0]=Array("field","",202,225);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",226,252);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",293,322);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",362,420);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1074,1109);
$z[4][4]['filename']="head.htm";
$z[5]=Array("list","\r\n     <a href=\"[field:arcurl/]\">\r\n    <div class=\"col-lg-4 col-sm-6 col-xs-12\">\r\n      <div class=\"course-list-img\"> <img src=\"[field:litpic/]\">\r\n        <div class=\"case-ms\">[field:description function=\"cn_substr(@me,56)\"/]... </div>\r\n      </div>\r\n      <li>[field:title/]</li>\r\n    </div>\r\n    </a>\r\n ",1981,2346);
$z[5][4]['row']="15";
$z[5][4]['pagesize']="10";
$z[5][4]['titlelen']="30";
$z[6]=Array("pagelist","",2460,2531);
$z[6][4]['listitem']="info,index,end,pre,next,pageno";
$z[6][4]['listsize']="5";
$z[7]=Array("include","",2912,2949);
$z[7][4]['filename']="footer.htm";

?>