<?php
$z[0]=Array("field","",202,225);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",226,252);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",293,315);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",355,406);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1060,1095);
$z[4][4]['filename']="head.htm";
$z[5]=Array("include","",1878,1915);
$z[5][4]['filename']="footer.htm";

?>