<?php
$z[0]=Array("field","",196,219);
$z[0][4]['name']="seotitle";
$z[1]=Array("global","",220,246);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",286,315);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",354,412);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1049,1084);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",1882,1911);
$z[5][4]['name']="position";
$z[6]=Array("include","",6214,6251);
$z[6][4]['filename']="footer.htm";

?>